### PR TITLE
Standard RPC Compatible

### PR DESCRIPTION
**Pull request by shunjizhan**
this PR includes #27 

## Change
this will make hardhat compatible with latest bodhi, which upgraded RPC behaviours to more standard way. More details: https://github.com/AcalaNetwork/bodhi.js/pull/323 

basically: removed loop helper which is not needed anymore

## Test
- without the loop helper, CI still pass with instant-sealing node https://github.com/AcalaNetwork/bodhi.js/runs/5717808839?check_suite_focus=true
- manually tested Token tutorial with normal sealing node, and all tests passed very stably

### CODE REVIEW

**Comment by ThunderDeliverer** [comment]
@shunjizhan I tested the behaviour and it seems fine without `wait()` in the local development network. How come we have this behaviour? It's preferable, just curious.. 🤔

**Comment by shunjizhan** [comment]
yeah I also did some more testing and it seems not to be reproduce-able anymore for token tutorials, however for this AAVE test I can reproduce it everytime
https://github.com/AcalaNetwork/aave-protocol-v2/pull/10/files#diff-9c8e1a59e198f5657620d1545a3d1e66e66ed292bf998770c67e81b38214562bR34

I am doing more digging to see what's the expected behavior.

**Comment by shunjizhan** [comment]
@ThunderDeliverer do you mind if I merge this to master? Already removed all the `tx.wait()`, since it still works for CI. and @ntduan is doing some package updates, which needs to be based on this branch, we should probably merge it before it gets too messy

**Comment by ThunderDeliverer** [comment]
@shunjizhan I noticed that an example in token tutorials consistently fails in the fresh network, but passes every other time (fails when you run it for the first time). Let me do some digging and if I manage to fix this behaviour, then I'm ok with merging it. Otherwise we need to deal with it some other way. I want the tests to pass if someone pulls them and runs them in order to see how our EVM+ behaves

**Comment by shunjizhan** [comment]
sure! I think I already figured it out, testing some new codes for the fix, will let you know once testing is finished

**Comment by ThunderDeliverer** [comment]
The issue is gone for me. I deleted `node_modules` and reinstalled them and now both the scripts and the tests pass 😅

**Comment by ThunderDeliverer** [comment]
I need to add the loop helper to the README in the AdvancedEscrow, so don't merge the branch just yet. I'll do it once the tutorial is updated.

**Comment by shunjizhan** [comment]
it can still sometimes fail, I believe if you try to limit your CPU to 5% and try again it will fail :zany_face: 
I will explain in more details in my following PR.

**Comment by shunjizhan** [comment]
actually, try run a local **normal-sealing** node, without `tx.wait()` it will fail for sure

**Review by ThunderDeliverer — APPROVED** [review]
Tested, rebased and already added the changes to the developer documentation 👌

**Comment by shunjizhan** [comment]
thanks for modifying add these docs!

**Pull request merged**
