### PR TITLE
Redesign loop

### PR DESCRIPTION
**Pull request by ThunderDeliverer**
Loop was redesigned, so that it uses createBlock RPC call in stead of continuously deploying the same smart contract again and again. This way there is no nonce clashes with the tests and scripts, when they are run in parallel.

### CODE REVIEW

**Comment by ThunderDeliverer** [comment]
@shunjizhan Here is the complete loop util redesign. Please don't merge the changes until I have the time to update the development documentation.

**Comment by shunjizhan** [comment]
wow the new loop helper does look super clean! I will take a closer look tomorrow and play around with ti

**Comment by ThunderDeliverer** [comment]
I'll leave the branch for now, if you want to experiment on it, but I already updated the docs, so we can delete it as well 😄

**Comment by shunjizhan** [comment]
played around with it, and it's very fast and stable, no flaky anymore, nice job! 

By the way maybe we can decrease the loop interval to 500 or 1000, which both speed up my tests from ~130s to ~70s. Previously we can't deploy contracts too fast, otherwise something wired will happen. Now that we have a clean helper to just trigger a new block, I think it's safe to decrease the interval to make tests run faster

**Pull request merged**
